Explicitly mark FlutterNetworkCapability public
When building the app for the first time using the plugin, the Java compilation cache is empty.

As of right now, this error comes up as the compiler can't find the compiled Kotlin class in the classpath:

```
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:144:error:cannot find symbol flutterEngine.getPlugins().add(newcom.nu.flutter_network_capabilities.FlutterNetworkCapabilitiesPluginO);

symbol:
class FlutterNetworkCapabilitiesPlugin

location: package com.nu.flutter_network_capabilities
```

This is caused by the lack of explicit `public` marker on the class. Without it, the Kotlin compiler does not produce a `.class` output for the class, as it cannot detect it's usage.

Adding a `public` solves the issue, even tho Android Studio considers it superfluous